apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z5q0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-z5q0@sha256:1160d4072a3b71af339cda2513d7c0eea9b313b8ae1c6dc95de2f755dc14ed04
        name: my-nodejs
        resources: {}
status: {}
